# This workflow will:
#   - download and start a NCTL docker image
#   - download the latest casper-java-sdk and build the jar
#   - upload the sdk jar as a project artifact
#   - download the test platform
#   - run the cucumber tests via gradle
#   - publish the xml test reports to the actions page


name: CSPR Java SDK Standard Tests
on:
  workflow_dispatch:
jobs:
  build:
    name: Java SDK Standard Tests
    runs-on: ubuntu-latest
    services:
      nctl:
        image: stormeye2000/cspr-nctl:1.5
        options: --name cspr-nctl
        env:
          PREDEFINED_ACCOUNTS: 'true'
          MINIMUM_ROUND_EXPONENT: '12'
          MAXIMUM_ROUND_EXPONENT: '14'
          DEPLOY_DELAY: '30sec'
        ports:
          - 11101:11101
          - 14101:14101
          - 18101:18101
          - 25101:25101
    steps:
      # Start the NCTL docker image
      - name: Starting the NCTL docker image
        run: |
          echo "Wait for NCTL"
          sleep 30s

      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x
 
      - name: Restore dependencies
        run: dotnet restore
 
      - name: Build
        run: dotnet build --no-restore
 
      - name: Test
        run: dotnet test --no-build
  
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: 'reports/*.xml'
          detailed_summary: true
          include_passed: true
          summary: true
